name: a_bit_of_health
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path_provider: ^2.0.2
  open_file: ^3.2.1
  syncfusion_flutter_pdf: ^19.1.69-beta
  universal_html: ^2.0.8
  io: ^1.0.0

  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.


  #Para Homepage
  carousel_pro: ^1.0.0
  url_launcher: ^6.0.3

  #Para History
  syncfusion_flutter_datepicker: ^19.1.67-beta
  syncfusion_localizations: ^19.1.67


  cupertino_icons: ^1.0.2
  html: ^0.15.0
  provider: ^5.0.0
  tuple: ^2.0.0
  intl: ^0.17.0
  firebase_storage: ^8.1.0
  firebase_core: ^1.0.2
  firebase_auth: ^1.1.4
  http: any
  shared_preferences: ^2.0.5
  dio: ^4.0.0
  fl_chart: ^0.35.0
 
 


provider:
  async: ^2.5.0
  path_provider: any
  numberpicker: ^1.3.0
  http: ^0.12.2
  path: ^1.7.0
  flutter_svg: ^0.19.3
  pool: ^1.5.0
  flutter_cache_manager: ^2.1.1
  permission_handler: ^4.4.0+hotfix.1
  downloads_path_provider: ^0.1.0


  
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  #   - images/a_dot_burr.jpeg
    - lib/assets/vaso_lleno.png
    - lib/assets/vaso_vacio.png
  #   - images/a_dot_ham.jpeg

  #para Homepage
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Mont
      fonts:
        - asset: fonts/Montserrat-SemiBold.ttf
    - family: Mont2
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
    - family: Mont3
      fonts:
        - asset: fonts/Montserrat-Italic.ttf
    - family: Sans
      fonts:
        - asset: fonts/OpenSansCondensed-LightItalic.ttf
    - family: Pt
      fonts:
        - asset: fonts/PTSansNarrow-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
